#ifndef GLOBAL_H
#define GLOBAL_H


#define CHUNK_WIDTH 16.0f
#define CHUNK_HEIGHT 256.0f
#define CHUNK_DEPTH 16.0f


#define WINDO_WIDTH 1600.0f
#define WINDOW_HEIGHT 1000.0f

#define RENDERER_FAR_PLANE_DISTANCE 1000.0f
#define RENDERER_NEAR_PLANE_DISTANCE 0.1f

// #define DEBUG_MODE



#endif // GLOBAL_H